### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Zekfad**

### CODE REVIEW

**Comment by Aixile** [comment]
Thanks!

**Comment by Aixile** [comment]
I will publish the change to the website later.

**Comment by Aixile** [comment]
@Zekfad 
Hi, the Russian translation is now published, as we are refactoring the site for major model updates, it took some time to backport the change. Anyway, thanks for your PR.

**Comment by Zekfad** [comment]
@Aixile I'll update tomorrow.

**Comment by Aixile** [comment]
@Zekfad  Hi, we made a major update to the site today.  Please check the site

**Comment by Zekfad** [comment]
@Aixile ok. Now on my workplace. let's check.

**Comment by Zekfad** [comment]
@Aixile there some questions about code. Can I ask your e-mail/or etc communication, just don't want to leave the "merge topic",

**Comment by Aixile** [comment]
@Zekfad Sure. Email me yanghujin94@gmail.com

**Comment by Aixile** [comment]
@Zekfad No, these apostrophes should not be deleted

**Comment by Zekfad** [comment]
@Aixile ok. And response from google mail: 
<details>
`550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipient's email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1 https://support.google.com/mail/?p=NoSuchUser v8sor14171724qkl.98 - gsmtp`
</details>

**Comment by Aixile** [comment]
@Zekfad I am sorry, I mistyped. yanghuajin94@gmail.com

**Pull request merged**
