### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Zekfad**
Edited translation.
But I not found many of site texts in original en_US file.
For example terms of use. Or about page.

I try to see code and there should be language settings for `/src/components/pages/`

### CODE REVIEW

**Comment by Aixile** [comment]
For  Terms of Use, we directly write to 
https://github.com/makegirlsmoe/makegirlsmoe_web/blob/master/src/components/pages/License.js

I have not internationalized all static pages in src/components/pages.

**Comment by Zekfad** [comment]
Can I Ask why?

**Comment by Aixile** [comment]
When I first made this site, I did not do the internationalization. 
I added Chinese and Japanese translations in last month, but I didn't have time to translate them all.

It seems that tips could be internationalized, but it is outdated, I will renew it soon.

**Comment by Zekfad** [comment]
@Aixile ok. Anyway now I'm adding some things for make internalize looks better. Happy to help!

**Comment by Zekfad** [comment]
I can't see localization function... Can you help me?
I'm trying to expect `src/components/Navbar.js` now.

**Comment by Aixile** [comment]
I think things in src/components/Navbar.js are already localized by editing the src/locale/ru_RU.js

**Comment by Aixile** [comment]
All "FormattedMessage" will be replaced by searching its id in the localization dictionary like ru_RU.js.

**Comment by Zekfad** [comment]
Not all.

**Comment by Aixile** [comment]
For 'Official Blog' and 'Github' we have not converted the text to FormattedMessage.

**Comment by Zekfad** [comment]
I can do this... In this pull.

**Comment by Zekfad** [comment]
fixed. but i should make localize for license. don't merge now.

**Comment by Zekfad** [comment]
Ok. Now I'm done translate navbar and license page full. Cuz you said that about page outdated. I don't change it.
Now I this that is all today.

**Comment by zhangjk95** [comment]
Thanks a lot!

**Comment by Zekfad** [comment]
No problem. Happy to help. Please message me, when new translate will be needed (my <a href="mailto:vorobevyaroslav@googlemail.com" title="vorobevyaroslav@googlemail.com">mail</a>).

**Comment by Zekfad** [comment]
And, if you need I can help to translate your blog (github.io).
And I think that i should add sign like "Please use English in your feedbacks" in license or in about page. Cuz' site looks translate, but you can't speak Russian.

**Pull request merged**
